spring.config.import=optional:file:.env[.properties],optional:configtree:./certs/
spring.application.name=libra_auction

# DataSource Configuration
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none

# Liquibase Configuration
spring.liquibase.enabled=false
# spring.liquibase.change-log=db/changelog/db.changelog-master.yaml

# Server Configuration
# server.port=8080
#server.servlet.context-path=/identity

# JWT Configuration
app.jwt.expiration=86400000
app.jwt.refreshable-duration=604800000

# Google OAuth2 Configuration
app.google.client-id=${GOOGLE_CLIENT_ID}
app.google.client-secret=${GOOGLE_CLIENT_SECRET}
app.google.redirect-uri=${GOOGLE_REDIRECT_URI}
